---
name: Class-DBI-Sweet
version: 0.10
author:
  - 'Christian Hansen <ch@ngmedia.com>'
  - 'Matt S Trout <mstrout@cpan.org>'
  - 'Andy Grundman <andy@hybridized.org>'
abstract: lib/Class/DBI/Sweet.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::DBI: v3.0.12
  DBD::SQLite: 1.08
  DBI: 0
  Data::Page: 0
  List::Util: 0
  SQL::Abstract: 1.55
recommends:
  Data::UUID: 0
provides:
  Class::DBI::Sweet:
    file: lib/Class/DBI/Sweet.pm
    version: 0.10
  Class::DBI::Sweet::SQL::Abstract:
    file: lib/Class/DBI/Sweet.pm
  Class::DBI::Sweet::Topping:
    file: lib/Class/DBI/Sweet/Topping.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
